Enforce bencode plugins to have required keys
log2timeline/plaso pull request #3337
Opened 2020-12-06 20:04 UTC by joachimmetz

Enforce bencode plugins to have required keys

2020-12-13 16:06 UTC, Onager requested changes

2020-12-13 17:33 UTC, joachimmetz commented on plaso/parsers/bencode_parser.py
> +class BencodeValue(object):
seeing the limited scope usage, SG, just note that it can represent a single value as well

2020-12-13 17:33 UTC, joachimmetz commented on plaso/parsers/bencode_parser.py
> +    """Closes the database."""
done

2020-12-13 17:36 UTC, joachimmetz commented on plaso/parsers/bencode_parser.py
> +    return BencodeValue(self.decoded_values).GetDecodedValue(name)
There should be nothing in the constructor to raise but agree with debug-ability

2020-12-13 17:38 UTC, joachimmetz commented
@Onager PTAL, changes made

2020-12-27 18:53 UTC, Onager approved these changes

2020-12-27 18:53 UTC, merged