implemented parser for Logd.0.log
log2timeline/plaso pull request #4062
Opened 2022-02-23 19:16 UTC by rick-slin

## One line description of pull request

## Description:

**Related issue (if applicable):** fixes #4061

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-02-27 07:25 UTC, joachimmetz commented
@rick-slin thx for the proposed changes, the CI tests are currently failing because the changes do not match the style guide https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html

2022-03-03 04:39 UTC, joachimmetz commented
assigning @jleaniz for a first review

2022-03-10 15:29 UTC, jleaniz commented on plaso/parsers/logd.py
> +  DATA_FORMAT = 'logd log'
Minor comment but I'd suggest to mention this is for iOS sysdiagnose logs as part of the description. 
```
DATA_FORMAT = 'iOS sysdiagnose log file'
```

2022-03-10 15:30 UTC, jleaniz commented on plaso/parsers/logd.py
> +class LogdEventData(events.EventData):
I suggest we change LogEventData to something more concrete like IOSysdiagnoseLogData or similar.

2022-03-10 15:33 UTC, jleaniz commented on plaso/parsers/logd.py
> +  DATA_TYPE = "logd:line"
suggestion: logd:line => ios_sysdiagnose_logd:line ?

2022-03-10 20:21 UTC, jleaniz requested changes
@rick-slin Thanks for the parser. I left some minor comments.

2022-03-16 14:20 UTC, jleaniz commented
@Onager please take a look when time permits.

2022-03-26 15:04 UTC, joachimmetz commented
@Onager is currently pre-occuplied

2022-03-26 15:05 UTC, joachimmetz commented on data/formatters/ios.yaml
> +  - 'Body: {body}'
consistency nit: use the same indentation, I'll change this

2022-03-26 15:07 UTC, joachimmetz commented on data/formatters/ios.yaml
> +data_type: 'logd:line'
add `ios`

2022-03-26 15:11 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +  DATA_TYPE = "ios_sysdiagnose_logd:line"
I also opt to use `ios:sysdiagnose:logd:line`

2022-03-26 15:12 UTC, joachimmetz commented on plaso/parsers/__init__.py
> +from plaso.parsers import ios_logd
style: nit use alphabetical order

2022-03-26 15:14 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +  """logd event data
Style nit: consider docstrings as sentences

2022-03-26 15:15 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    logger (str): process that submits the log event
style nit: alphabetical ordering

2022-03-26 15:35 UTC, joachimmetz reviewed
Numerous style nits, I'll make the changes

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    self.logger = None
style nit: alphabetical ordering

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +  NAME = 'logd.0.log'
Note that this is the name of the parser not the file

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +  _LOGGER = pyparsing.SkipTo(':')('logger') + pyparsing.Suppress(': ')
Use the long form `setResultsName` which is much easier to read/understand

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    """Parses a log record structure and produces events.
style nit: add an empty line

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    if key != 'log_entry':
style nit: indentation does not align with docstring

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    time_deta_hours = time_delta[:3]
I assume `deta` should be `delta`

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    time_offset = -1 * int(time_deta_hours) * 60 + int(time_delta[3:])
use int(value, 10) and catch ValueError

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +    """Verifies that this is a mobile installation log file.
`mobile installation log file` copy paste error ?

2022-03-26 15:35 UTC, joachimmetz commented on plaso/parsers/ios_logd.py
> +class IOSysdiagnoseLogdData(events.EventData):
Missing S? `IOSSysdiagnoseLogdData`

2022-03-26 15:35 UTC, joachimmetz commented on tests/parsers/ios_logd.py
> +"""Tests for the iOS Mobile Installation log parser."""
`iOS Mobile Installation log parser` copy paste error?

2022-03-26 15:35 UTC, joachimmetz commented on tests/parsers/ios_logd.py
> +class IOSysdiagnoseLogdUnitTest(test_lib.ParserTestCase):
Missing S ?

2022-03-26 15:35 UTC, joachimmetz commented on tests/parsers/ios_logd.py
> +        'body': 'libtrace_kic=1'
just put the } at the end of the last line

2022-03-26 15:45 UTC, joachimmetz commented
@rick-slin @jleaniz left some comments mostly for educational purposes, made the changes already

2022-03-26 15:46 UTC, joachimmetz approved these changes
LGTM after latest changes

2022-03-26 16:39 UTC, jleaniz approved these changes

2022-03-26 16:41 UTC, joachimmetz commented on data/formatters/ios.yaml
> +data_type: 'logd:line'
says:
```
---
type: 'conditional'
data_type: 'ios:sysdiagnose:logd:line'
message:
- 'Logger: {logger}'
```

for me, are you looking at an outdated version?

2022-03-26 16:43 UTC, jleaniz commented on data/formatters/ios.yaml
> +data_type: 'logd:line'
This was an old comment/change that had been requested. Closing this as resolved in your last commit :)

2022-03-27 04:59 UTC, merged