implemented parser for iOS lockdown daemon log
log2timeline/plaso pull request #4068
Opened 2022-04-06 18:30 UTC by rick-slin

## One line description of pull request
implemented parser for iOS lockdown daemon log

## Description:
implemented parser for iOS lockdown daemon log

**Related issue (if applicable):** fixes #4067

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-04-11 14:14 UTC, jleaniz commented on plaso/parsers/ios_lockdownd.py
> +
remove empty line

2022-04-11 14:17 UTC, jleaniz commented on test_data/lockdownd.log
> +10/13/21 07:57:42.865446 pid=69 mglog: libMobileGestalt MGBasebandSupport.c:183: No IMEI in CT mobile equipment info dictionary
Could we please rename the test data file ios_lockdownd.log? This way it's clearer what it's for.

2022-04-11 14:17 UTC, jleaniz requested changes
Thanks for the parser! Left some minor comments for you to address.

2022-04-16 08:47 UTC, joachimmetz commented on plaso/parsers/ios_lockdownd.py
> +  def ParseRecord(self, parser_mediator, key, structure: object):
pytype information not yet supported by this code base due to version differences in pytype definitions

2022-04-16 08:47 UTC, joachimmetz commented on plaso/parsers/ios_lockdownd.py
> +    year = 2000 + self._GetValueFromStructure(structure, 'two_digit_year')
What if _GetValueFromStructure returns None ?

2022-04-16 08:50 UTC, joachimmetz commented on tests/parsers/ios_lockdownd.py
> +                'interrupted" }\n}',
remove `\n` from the value also leading space can be removed

2022-04-16 08:52 UTC, joachimmetz commented
left some comments for educational purposes, made the changes already

2022-04-17 04:11 UTC, merged