Added parser for Atlassian Confluence access logs
log2timeline/plaso pull request #4123
Opened 2022-06-03 14:15 UTC by Onager

## One line description of pull request

Parser for Confluence access logs

## Description:

**Related issue (if applicable):** fixes #<plaso issue number here>

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-06-05 13:26 UTC, joachimmetz commented
@Onager test are failing, could you PTAL

2022-06-05 13:28 UTC, joachimmetz commented on plaso/parsers/confluence_access.py
> +    http_request_method (str): http request method.
in doc string please rename 'http' to 'HTTP'

2022-06-05 13:28 UTC, joachimmetz commented on plaso/parsers/confluence_access.py
> +    http_request_method (str): http request method.
also for URI and URL

2022-06-05 13:32 UTC, joachimmetz commented on plaso/parsers/confluence_access.py
> +
remove this empty line

2022-06-05 13:38 UTC, joachimmetz requested changes
Some small nits.

2022-06-10 13:28 UTC, Onager commented on plaso/parsers/confluence_access.py
> +
Done

2022-06-11 04:14 UTC, joachimmetz approved these changes
LGTM

2022-06-11 04:14 UTC, merged