Added tag for system waking from sleep
log2timeline/plaso pull request #4153
Opened 2022-07-15 14:44 UTC by honorthecode

Event ID- 1 from source- Microsoft-Windows-Power-Troubleshooter explicitly identifies that the system has returned from a low power state. The event also contains the exact times that the system went to sleet and woke up, as opposed to when sleep mode was initiated.

Refer to the screenshot in https://answers.microsoft.com/en-us/windows/forum/all/windows-wakes-up-unwantedly/fc50b926-3a26-420d-aa91-6ba796ca7f2a for an example.

This event could have its own tag as proposed or it could also make sense to add it to the system start events tag.

## One line description of pull request

## Description: Edit plaso/data/tag_windows.txt to add tag for system waking from sleep.

**Related issue (if applicable): N/A

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [x] Automated checks (Travis, Codecov, Codefactor )pass
  - [x] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-07-15 14:50 UTC, honorthecode commented
How can I request a reviewer for the change?

2022-07-15 20:36 UTC, joachimmetz commented
please add an unit test for this tagging rule

2022-07-15 20:37 UTC, joachimmetz requested changes
missing test

2022-07-20 22:14 UTC, honorthecode commented
@joachimmetz this is my first time submitting a pull request and hopefully I did the unit test as intended in [https://plaso.readthedocs.io/en/latest/sources/developer/Testing.html#unit-tests](https://plaso.readthedocs.io/en/latest/sources/developer/Testing.html#unit-tests) :

```
~/Tools/plaso$ python run_tests.py
Using Python version 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
Checking availability and versions of dependencies.
[OK]            artifacts version: 20220219
[OK]            bencode
[OK]            certifi version: 2021.05.30
[OK]            cryptography version: 2.8
[OK]            dateutil version: 2.8.1
[OK]            defusedxml version: 0.7.1
[OK]            dfdatetime version: 20220131
[FAILURE]       dfvfs version: 20210606 is too old, 20220414 or later required
[OK]            dfwinreg version: 20211207
[OK]            dtfabric version: 20220219
[OK]            future version: 0.18.2
[OK]            lz4 version: 4.0.0
[OPTIONAL]      missing: opensearchpy
[OK]            pefile version: 2021.9.3
[OK]            psutil version: 5.9.0
[OK]            pybde version: 20220121
[OK]            pycreg version: 20210625
[OK]            pyesedb version: 20210424
[OK]            pyevt version: 20210424
[OK]            pyevtx version: 20210525
[OK]            pyewf version: 20140812
[OK]            pyfsapfs version: 20210424
[OK]            pyfsext version: 20220319
[OK]            pyfshfs version: 20220427
[OK]            pyfsntfs version: 20220220
[OK]            pyfsxfs version: 20220113
[OK]            pyfvde version: 20220125
[OK]            pyfwnt version: 20210906
[OK]            pyfwsi version: 20220123
[OK]            pylnk version: 20210417
[OK]            pyluksde version: 20220121
[OK]            pymodi version: 20210807
[OK]            pymsiecf version: 20210420
[OK]            pyolecf version: 20210512
[OK]            pyparsing version: 2.4.7
[FAILURE]       missing: pyphdi
[OK]            pyqcow version: 20210419
[OK]            pyregf version: 20220131
[OK]            pyscca version: 20210419
[OK]            pysigscan version: 20220124
[OK]            pysmdev version: 20210418
[OK]            pysmraw version: 20210807
[OK]            pytsk3 version: 20211111
[OK]            pytz version: 2021.1
[OK]            pyvhdi version: 20210425
[OK]            pyvmdk version: 20210807
[OK]            pyvsgpt version: 20211115
[OK]            pyvshadow version: 20211114
[OK]            pyvslvm version: 20210807
[OK]            redis version: 3.5.3
[OK]            requests version: 2.25.1
[OK]            six version: 1.16.0
[OK]            urllib3 version: 1.26.7
[OPTIONAL]      missing: xattr
[OK]            xlsxwriter version: 3.0.3
[OK]            yaml version: 5.3.1
[OK]            yara version: 4.2.0
[OK]            zmq version: 22.3.0
```

2022-07-21 03:07 UTC, joachimmetz commented
With `missing test` I mean add an unit test for this tagging rule to https://github.com/log2timeline/plaso/blob/main/tests/data/tag_windows.py

2022-08-03 04:54 UTC, joachimmetz commented
note: rebased branch to see changes

2022-08-09 16:12 UTC, honorthecode commented
@joachimmetz I apologize in advance if you have answered this in the plaso documentation but I could not find how to add a unit test for a rule to the file you specified. Its my first time contributing to open source and I'm not doing that well :-|.

2022-08-09 16:22 UTC, joachimmetz commented
@honorthecode I think @Onager already added one, this might not be documented

2022-08-09 21:15 UTC, honorthecode commented
Thanks @joachimmetz. Are we waiting for that to play out then?

2022-08-10 01:56 UTC, joachimmetz commented
> Are we waiting for that to play out then?

who is waiting for what?

2022-08-10 02:17 UTC, joachimmetz commented
Added provider identifier to make the tagging rule more robust.

2022-08-10 05:28 UTC, joachimmetz approved these changes
LGTM now

2022-08-10 05:29 UTC, merged