Update cloudtrail parser
log2timeline/plaso pull request #4187
Opened 2022-08-09 19:21 UTC by alexgoedeke

## One line description of pull request

add current log format for aws cloudtrail parser.

## Description:

**Related issue (if applicable):** fixes #4182 

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-08-09 22:24 UTC, jleaniz commented
@alexgoedeke Thanks for the contribution! At first glance, it seems like the test data you are using here differs from the test data in the original parser (e.g. not in JSONL format) and more closely matches what is provided in  https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-examples.html - looks like the format is in fact JSON and not JSONL. @jonathan-greig

2022-09-02 03:10 UTC, jonathan-greig commented
Hi Alexander, thanks for this PR but Juan is correct that the Cloudtrail log parser is designed for logs saved in JSON-L format and your changes seem to change the parser to use JSON. [dftimewolf](https://github.com/log2timeline/dftimewolf) with the `aws_logging_collect` can be used to save cloudtrail logs in JSON-L format.

2022-09-02 03:35 UTC, jleaniz commented
@alexgoedeke I think it would make sense to have this parser in addition to the existing one, rather than as a replacement. This new parser would seem to work on log data directly exported from AWS Cloudtrail. Would you be willing to adjust this PR accordingly?

2022-09-05 08:38 UTC, alexgoedeke commented
@jleaniz Yes, this makes sense. I adjusted the PR accordingly.

2022-09-10 13:05 UTC, joachimmetz commented
@alexgoedeke how is this parser different from https://github.com/log2timeline/plaso/blob/main/plaso/parsers/jsonl_plugins/aws_cloudtrail_log.py ?

2022-09-10 13:12 UTC, joachimmetz requested changes
Unclear how this parser differs from the current JSON-L plugin

2022-09-10 13:12 UTC, joachimmetz commented on plaso/parsers/aws_cloudtrail_log.py
> +"""JSON-L parser plugin for AWS CloudTrail log files.
Per comment thread, is this a JSON or JSON-L parser?

2022-09-10 13:12 UTC, joachimmetz commented on plaso/parsers/aws_cloudtrail_log.py
> +from plaso.containers import events
style nit: order alphabetically

2022-09-10 13:12 UTC, joachimmetz commented on plaso/parsers/aws_cloudtrail_log.py
> +    eventTime
style nit: missing docstrings and docstring does not match the actual attribute names

2022-09-10 13:12 UTC, joachimmetz commented on plaso/parsers/aws_cloudtrail_log.py
> +    'userIdentity': 'user_identity',
Use 4 spaces as continuation indentation (repeat this in other places)

2022-09-10 13:12 UTC, joachimmetz commented on tests/parsers/aws_cloudtrail_log.py
> +        "event_version": "1.0",
style nit: plaso codebase uses single quotes

2022-09-10 13:12 UTC, joachimmetz commented on tests/parsers/aws_cloudtrail_log.py
> +
style nit: missing empty line

2022-11-01 05:40 UTC, joachimmetz commented
@alexgoedeke what is the status of this? Should I close this PR for now and reopen when you have the time work on it?

2023-03-26 08:42 UTC, joachimmetz commented
per previous comment closing PR for now

2023-03-26 08:42 UTC, closed without merging