Update aws elb parser
log2timeline/plaso pull request #4189
Opened 2022-08-09 20:03 UTC by alexgoedeke

## One line description of pull request

update aws elb parser to support classic and network loadbalancer logs

## Description:

**Related issue (if applicable):** fixes #4188

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

2022-08-09 22:04 UTC, jleaniz requested changes
@alexgoedeke Thank you for the parser enhancements! Some minor comments/questions but the changes look good.

2022-08-15 15:33 UTC, jleaniz approved these changes

2022-09-10 07:38 UTC, joachimmetz commented on plaso/parsers/aws_elb_access.py
> +  _WORD = pyparsing.Word(pyparsing.printables) | BLANK | pyparsing.Literal('-')
BLANK already includes `pyparsing.Literal('-')` ?

2022-09-10 07:41 UTC, joachimmetz commented on plaso/parsers/aws_elb_access.py
> +          .setParseAction(pyparsing.removeQuotes) +
break line after .setParseAction(

2022-09-10 07:41 UTC, joachimmetz commented on plaso/parsers/aws_elb_access.py
> +    ('elb_application_accesslog', _LOG_LINE_APPLICATION),
codebase uses 4 spaces for continuation indentation

2022-09-10 07:45 UTC, joachimmetz commented on plaso/parsers/aws_elb_access.py
> +    if key == 'elb_application_accesslog' and \
don't use `\' to break up lines

2022-09-10 07:51 UTC, joachimmetz commented on tests/parsers/aws_elb_access.py
> +    # pylint: disable=line-too-long
don't do this

2022-09-10 17:43 UTC, joachimmetz approved these changes
LGTM

2022-09-10 17:44 UTC, merged