Updated GC log parser to include status fields
log2timeline/plaso pull request #4918
Opened 2024-10-17 17:04 UTC by tmoney-coder

## One line description of pull request

Added parsing for protoPayload.status.message and protoPayload.status.details[0].reason to the Google Cloud log parser

## Description:

This adds parsing for additional data from Google Cloud logs. Specifically the `protoPayload.status`. This now parses the `status.message` and `status.details[0].reason` fields into status_message and status_reason respectively. 

This has been tested using dftimewolf to download the data and pass it to a custom container and tested locally.

**Related issue (if applicable):** fixes #<plaso issue number here>
Fixing issue https://github.com/log2timeline/plaso/issues/4917

## Notes:
All contributions to Plaso undergo [code review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc).
This makes sure that the code has appropriate test coverage and conforms to the
[Plaso style guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
* [x] Automated checks (GitHub Actions, AppVeyor) pass
* [x] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
* [x] Reviewer assigned

2024-10-17 17:29 UTC, joachimmetz commented
Thanks for the proposed changes, @sydp would you like to take a first look at these changes?

2024-10-18 21:40 UTC, sydp requested changes
Is it possible to update the corresponding test data and unit tests to include these new changes?

2024-10-18 21:40 UTC, sydp commented on plaso/parsers/jsonl_plugins/gcp_log.py
> +    status_message (str): the status message of the event
style nit: please add fullstops for these.

2024-10-18 21:40 UTC, sydp commented on plaso/parsers/jsonl_plugins/gcp_log.py
> +      event_data.status_message = self._GetJSONValue(status,'message')
style nit: here and for similar ones below, add a space between arguments i.e. `self._GetJSONValue(status,'message')` -> `self._GetJSONValue(status, 'message')`

2024-10-28 21:54 UTC, tmoney-coder commented
Updated but test seem to be timing out today

2025-02-23 10:33 UTC, joachimmetz commented
@sydp what is the status of the review?

2025-02-23 10:56 UTC, sydp commented
> @sydp what is the status of the review?

Review was pending updates to tests.

2026-05-10 07:08 UTC, joachimmetz commented
Rebased with HEAD

2026-05-10 07:09 UTC, joachimmetz commented
After rebase not much left in this PR, closing it

2026-05-10 07:09 UTC, closed without merging